# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c2f39e0a3b52144ab90830dec241561f385ee0dfdfcb7fbbc2f1e866d09ade06ededdb9a015ce10f4ea79c643e1689a604a504ead0d646df9f05f6b3157990f

test:
  secret_key_base: b0c5f3ac55c16ca65dbc8d9ac34b2cb3d04240e3e75c122c986dda6aa63cf92c7f6aacf6d7d492dc1f8b133bb37537afae772cb7ea4589139b0a066284c0e0a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
